### ISSUE TITLE
zip은 추출이 안되나요?

### ISSUE THREAD

**Issue by udonsari0101** [cg10036/Kyobo-EBOOK-PDF#1]
코드 수정하면 가능할까요

**Comment by cg10036** [comment]
안녕하세요, ebook 링크 주시면 확인해보겠습니다.

**Comment by udonsari0101** [comment]
https://wviewer.kyobobook.co.kr/newComicMobileViewer/OGRjMmU5OTlhMjQ3ODkzZjk1YmNhNmFmYjAwZTM3NDQwNjM3OTJiNTFhOWI0OWE1NjRhYmQ2NjJhNjEzNTk3OQ==

**Comment by cg10036** [comment]
링크 접속이 안됩니다. ebook 구매 링크로 주시겠어요?

**Comment by udonsari0101** [comment]
https://ebook-product.kyobobook.co.kr/dig/epd/ebook/E000003513970

**Comment by cg10036** [comment]
PDF의 경우 DRM이 적용되어 있지 않지만, Epub, ZIP의 경우 DRM이 적용되어 있습니다.

대한민국 저작권법 제104조의2에 따르면, 누구든지 정당한 권한 없이 기술적 보호조치를 제거, 변경하거나 우회해서는 안 됩니다. 그러나 몇 가지 예외가 있으며, 그중 하나는 "정당한 권한을 가지고 프로그램을 사용하는 자가 다른 프로그램과의 호환을 위하여 필요한 범위에서 프로그램코드역분석을 하는 경우"입니다. 이는 제가 직접 분석하는 경우에는 허용됨을 의미합니다.

다만, DRM을 해제하는 프로그램을 공유하는 것은 문제가 될 수 있습니다. 이는 저작권법 제104조의2 제2항에 따라 "기술적 보호조치를 무력화하는 것을 가능하게 하거나 용이하게 하는 것을 주된 목적으로 고안, 제작, 개조되거나 기능하는 것"에 해당하기 때문입니다.

따라서 Epub, ZIP과 같이 DRM이 적용된 EBook의 경우 해당 추출기에서 지원하지 않을 예정입니다.
